PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: prohousing.no
    exposer: Ingress
    http: "true"
    tlsacme: "false"
    urltemplate: '{{.Service}}-{{.Namespace}}.{{.Domain}}'
ph-istio:
  istio:
    enabled: true
jenkins:
  Servers:
    Global: {}
prow: {}
